### ISSUE TITLE
Update message also when updated

### ISSUE THREAD

**Issue by crymates** [ModdedMinecraft/MMCTickets#1]
I updated to 0.2, still get the message ingame and in console.

` [Server thread/INFO] [mmctickets]: You are not running the latest recommended build! Recommended build is: 0.2`

**Comment by crymates** [comment]
Also deleted whole config and let it rebuild, didn't fixed it.

**Comment by leelawd** [comment]
Whoops, looks like i forgot to change one of the checks. Its fixed in 0.3
