### ISSUE TITLE
Request: MySQL integration

### ISSUE THREAD

**Issue by Foxgreat** [ModdedMinecraft/MMCTickets#10]
Can you add mysql connection to your plugin please? Thank you!

To assosiate base of players with LuckPerms base and add external Tickets base. To collect tickets in server and have cross-server access.

**Comment by Foxgreat** [comment]
Feature of choose from mysql or h2 BD collection if to be correct

**Comment by leelawd** [comment]
I honestly would love to have MySQL integration but i honestly have no clue on how to code it in :( at least for now. However this will be a feature at some point, i just don't know exactly when.

**Comment by Foxgreat** [comment]
got it, stay this request, may be me or someone else will help with it

**Comment by leelawd** [comment]
Took some time, i apologise, This will be in the next update.
