### ISSUE TITLE
./ticket tp and /ticket teleport not working

### ISSUE THREAD

**Issue by DragaoNimhe** [ModdedMinecraft/MMCTickets#12]
Hey there, got your ticket plugin working but we've encountered another issue.... /ticket tp and /ticket teleport aren't working for us. All other aspects of the plugin function but when we type those, we just get "Input command tp(/teleport) is not a valid subcommand!" Hopefully you can help with this, as being able to teleport to issues is the main reason we want a ticket plugin!

**Comment by leelawd** [comment]
I feel like an idiot with this. lol.

As a side note, you can also teleport using the chat GUI by clicking on the coordinates in the ticket itself, But the command should now work as intended

Fixed in 1.4.2
