### ISSUE TITLE
Different Languages

### ISSUE THREAD

**Issue by AokuYuki** [ModdedMinecraft/MMCTickets#14]
Hi there, i really love this plugin!
I couldnt find any translation for the messages.
Did i oversee them or do they not exist?
In case they not exist, i offer to translate into german.

kind regards
Yuki

**Comment by leelawd** [comment]
Thank you for your support.

At the moment there is no translations available, The only way for me to give default translations in the format that this is currently coded would be to provide a different messages.conf somewhere with the translations in for the end-user to replace the default messages.conf with.

I only know English so it is impossible for me to accurately provide these translations but if you are willing to help out, all i would need is just the translated messages.conf and i could work it in from there.

**Comment by AokuYuki** [comment]
Here is a translation of message.conf i made:
https://pastebin.com/7SLZPz0h

Would be nice if the rest could somehow translated too.
