### ISSUE TITLE
Plugin consuming a lot of time on avg. 

### ISSUE THREAD

**Issue by ghost** [ModdedMinecraft/MMCTickets#5]
According to sponge's timing report for my server: https://timings.aikar.co/?id=bc01d2ec645549c2b94ff5af179f5f99#timings

It would seem your plugin is causing severe and steady TPS drops on our server. This timing report isnt the best example as far as the graph in the top right however, we see our TPS drop to 4/20 often esp with around 3-5 players. I have a server with 8 gigs of ram so we should not be experiencing slowdowns like this with such few players. 

Sadly I will need to temp remove this plugin temp as the server cannot run with it doing this. I consider this a core functionality of our server and have been pushing VERY hard for the players to use it. I will be watching for updates to it and will be excited to be able to reinstall.

**Comment by leelawd** [comment]
Very interesting, I haven't been experiencing these types of issues myself even though we run a 20-30 player server.

However, I will take a look into the listeners and see if i can improve on them.

**Comment by leelawd** [comment]
Do you know if this issue has been ongoing or has appeared after a spongeforge update?

**Comment by ghost** [comment]
I sadly have not been watching for that. Just recently started tightening everything down before releasing, I am on the latest SpongeForge (1.10.2-2281-5.2.0-BETA-2407).

I have however been noticing TPS drops randomly with only a few players on so while I haven't been watching the timings report, I would venture to guess it might have been going on before the upgrade. 

I know that provides you with little to no help... I'm sorry!

Below is my Nucleus Info for an easy to view list. I believe this was made before I removed MMCTickets. 

[nucleus-info-20170622-153008 (1).txt](https://github.com/ModdedMinecraft/MMCTickets/files/1098431/nucleus-info-20170622-153008.1.txt)

**Comment by leelawd** [comment]
Closing this in hopes that this is no longer an issue. I cannot replicate this at least. If it still is an issue please submit another.
