### ISSUE TITLE
Suggestion: Allow comment edits/overwrite

### ISSUE THREAD

**Issue by SubtypeZero** [ModdedMinecraft/MMCTickets#6]
I think it would be nice if I could do something like /ticket comment -o <ticket#> <comment> to overwrite an existing comment. Another idea would be to show "There is already a comment on this ticket." and if you have permission to edit, show something like "Would you like to edit the existing comment?" and you could click to confirm.

**Comment by leelawd** [comment]
Added this in 1.3.0 :)

https://ore.spongepowered.org/leelawd93/MMCTickets/versions/1.3.0
