### ISSUE TITLE
Error occurred while executing command

### ISSUE THREAD

**Issue by MaegnusTheBlackMage** [ModdedMinecraft/MMCTickets#7]
Playing on sponge for 1.12.2 and when I run any command i get the following error:

Error occurred while executing command: org.spongepowered.api.service.pagination.PaginationList$Builder.sendTo(Lorg/spongepowered/api/text/channel/MessageReceiver;)V

**Comment by leelawd** [comment]
https://ore.spongepowered.org/leelawd93/MMCTickets/versions/1.4.0-API7
